### ISSUE TITLE
Twitter converts images to JPEG

### ISSUE THREAD

**Issue by notpushkin** [Francesco149/gweet#2]
Depending on contents of the screenshot, this might be undesired. However, this [can be prevented](https://github.com/iamale/screentweet) (tl;dr: make some pixels semi-transparent). It might be nice to integrate this technique into your tool as well.

**Comment by Francesco149** [comment]
interesting, I should probably test and see if just slightly lowering the alpha on the first pixel achieves the same result.

**Comment by notpushkin** [comment]
> just slightly lowering the alpha on the first pixel

This works for me as well, I was just too lazy to rewrite the script for this (and was doing it manually in GIMP instead, ugh).

**Comment by notpushkin** [comment]
Yeah, it works: https://twitter.com/iamale_ru/status/877651482904076288

**Comment by Francesco149** [comment]
oops, sorry for all the references, I was cleaning up git history since this repo has few commits

**Comment by Francesco149** [comment]
anyways @iamale if you get the chance, please test the new binaries. I switched to statically linking against musl and I haven't tested it on non-musl distros:

https://github.com/Francesco149/gweet/releases/tag/v1.1.2

**Comment by notpushkin** [comment]
@Francesco149 Just tested, works like a charm! Thank you.

**Comment by Francesco149** [comment]
good, thanks for testing
